const questions = [
  { id: 'violence', text: 'How much has exposure to violence affected you?', followUp: { condition: 4, key: 'violence_followup', text: 'Can you describe how violence has impacted your relationships?' } },
  { id: 'divorce', text: 'How much has divorce impacted your life?', followUp: { condition: 4, key: 'divorce_followup', text: 'How has divorce influenced your views on commitment?' } },
  { id: 'neglect', text: 'How much has neglect influenced your experiences?', followUp: { condition: 4, key: 'neglect_followup', text: 'In what ways has neglect affected your self-esteem?' } },
  { id: 'illness', text: 'How much has illness shaped your life?', followUp: { condition: 4, key: 'illness_followup', text: 'How has illness changed your perspective on health?' } },
  { id: 'money', text: 'How much have financial issues affected you?', followUp: { condition: 4, key: 'money_followup', text: 'How have financial struggles impacted your goals?' } },
  { id: 'estrangement', text: 'How much has estrangement impacted you?', followUp: { condition: 4, key: 'estrangement_followup', text: 'How has estrangement affected your sense of family?' } },
  { id: 'addiction', text: 'How much has addiction affected your life?', followUp: { condition: 4, key: 'addiction_followup', text: 'How has addiction influenced your trust in others?' } },
  { id: 'death', text: 'How much has the loss of a loved one influenced you?', followUp: { condition: 4, key: 'death_followup', text: 'How has this loss shaped your views on mortality?' } },
  { id: 'trust', text: 'How important is trust to you?', followUp: { condition: 4, key: 'trust_followup', text: 'How do you rebuild trust after it’s been broken?' } },
  { id: 'communication', text: 'How important is communication to you?', followUp: { condition: 4, key: 'communication_followup', text: 'What communication style works best for you?' } },
  { id: 'conflict', text: 'How do you handle conflict?', followUp: { condition: 4, key: 'conflict_followup', text: 'What strategies do you use to resolve conflicts?' } },
  { id: 'religion', text: 'How important is religion to you?', followUp: { condition: 4, key: 'religion_followup', text: 'How does religion influence your daily life?' } },
  { id: 'politics', text: 'How important are political views to you?', followUp: { condition: 4, key: 'politics_followup', text: 'How do political differences affect your relationships?' } },
  { id: 'resilience', text: 'How resilient do you consider yourself?', followUp: { condition: 4, key: 'resilience_followup', text: 'What helps you bounce back from challenges?' } },
  { id: 'extroversion', text: 'How extroverted are you?', followUp: { condition: 4, key: 'extroversion_followup', text: 'How does your extroversion affect your social life?' } },
  { id: 'risk', text: 'How comfortable are you with taking risks?', followUp: { condition: 4, key: 'risk_followup', text: 'What’s the biggest risk you’ve taken?' } },
  { id: 'empathy', text: 'How empathetic are you?', followUp: { condition: 4, key: 'empathy_followup', text: 'How do you show empathy in relationships?' } },
  { id: 'tradition', text: 'How important are traditions to you?', followUp: { condition: 4, key: 'tradition_followup', text: 'What traditions are most meaningful to you?' } }
];